### ISSUE TITLE
Pregunta: Como conseguir una cuenta?

### ISSUE THREAD

**Issue by TomMalbran** [alejoasotelo/andreani-sdk-rest#1]
Hola. Estoy hace tiempo tratando de conseguir funcionar el API, y el problema es que la cuenta no funciona. Intente obtenerla desde https://developers.andreani.com/como-empezar/credenciales, y me cree una cuenta. Pero esos datos no me sirven para usar el API Rest. Intente contactarme con Andreani, pero todavía no me han respondido a lo pedido.

Quería saber cómo lograste conseguir una cuenta para usar al API Rest. Muchas gracias.

**Comment by alejoasotelo** [comment]
Hola @TomMalbran enviales un mail a webservicecasa@andreani.com y deciles que queres usar la nueva api. Yo les tuve que hacer el mismo reclamo y me pasaron los datos. Cualquier cosa avisa!

**Comment by TomMalbran** [comment]
Gracias @alejoasotelo. Ayer les envíe el reclamo. Estoy esperando a que me respondan con la cuenta.
