### ISSUE TITLE
Tarifas y Crear Orden v2

### ISSUE THREAD

**Issue by TomMalbran** [alejoasotelo/andreani-sdk-rest#2]
Hola
Un par de APIs que faltan.

1. Para cotizar el pedido vi que agregaron un api de tarifas a la versión 1.

2. Agregaron una nueva forma de crear los pedidos en la versión 2. La versión 1 del api no me funcionaba, pero esta segunda si.

Ambos APIs los agregue localmente y funcionan bien.

**Comment by alejoasotelo** [comment]
Gracias por el dato, me habían dicho hace unos meses que lo iban a implementar. En cuanto tenga tiempo lo implemento y actualizo.

Respecto a la nueva forma de crear pedidos lo reviso!

**Comment by alejoasotelo** [comment]
@TomMalbran Acabo de  agregar las funcionalidades. La función cotizarEnvio(), podés ver un ejemplo en example.php y además a la función addOrden le agregué una parámetro para poder cambiar la versión de la Api a usar.
Ejemplo:
```php
// Por default usa la versión 1.
$result = $ws->addOrden($data, Andreani::API_V2);
```` 

Cualquier otra pregunta, ayuda, idea, no dudes en decirme, saludos!

**Comment by TomMalbran** [comment]
Buenísimo. Un detalle. Probaste la versión de enviar orden? Para implementarlo tuve que primero usar json_encode sobre los datos para que funcione.

```php
return $this->makeRequest($uri, 'post', json_encode($data));
```

**Comment by alejoasotelo** [comment]
Esto ya está listo, agregué la opción de enviar un array o directamente el json string (json_encode). Cualquier otra corrección que notés o quieras aportar sentite libre de enviar un pull request. 

Abrazo!

**Comment by lalfonso86** [comment]
buenas, como envio en el json los datos del remito?
