### ISSUE TITLE
Nro de Orden vs Nro de Envío en bulto

### ISSUE THREAD

**Issue by lnzzz** [alejoasotelo/andreani-sdk-rest#3]
Hola Alejo! Antes que nada agradecerte por el gran laburo que hiciste con la librería REST de Andreani.

Quería consultarte una duda que me surge a la hora de utilizarla.

Cuando yo obtengo la orden, la misma puede tener N cantidad de bultos.
Cada bulto tiene un numero de envío distinto, pero la orden sigue manteniendo el mismo.

A la hora de checkear el estado de la orden en general, debería checkear el estado de cada uno de los bultos o no existe tal cosa como un estado de orden general?

Desde ya mil gracias y saludos!

**Comment by alejoasotelo** [comment]
Hola @lnzzz , muchas gracias!

Cuando se crea una orden, cada bulto se genera con un número de envío (identificador del bulto). La orden en si, no genera ningun id. Estos números de envío de cada bulto quedan asociados a la orden. Es decir, que cuando obtengas la orden con el número de envío de algún bulto, vas a recibir la orden con todos sus bultos.

Ejemplo:
- Orden A
  - Bulto 1A
  - Bulto 2A
-Orden B
  - Bulto 1B

Al obtener la orden con el número de envío del bulto 1A (getOrden) vas a obtener la Orden A con sus bultos 1A y 2A. Si la obtenes con el número de envío del bulto 2A vas a obtener la misma orden.
Al obtener la orden con el número de envío del bulto 1B, vas a obtener la Orden B.

Cómo obtenés los estados de las ordenes?
Deberías chequear la trazabilidad de cada bulto. En la api v2 que usa Ordenes y no Envíos, no hay un estado general. En la v1 había un estado.
Además tené en cuenta que en modo debug no funciona bien la trazabilidad, a veces el request devuelve código 500 o 404. Te aviso porque posiblemente no puedas hacer pruebas.

**Comment by lnzzz** [comment]
Clarísimo como el agua! Mil millones de gracias de nuevo!

Un abrazo y buen finde!
