### ISSUE TITLE
Class 'AlejoASotelo\Andreani' not found

### ISSUE THREAD

**Issue by cruzdelsur3** [alejoasotelo/andreani-sdk-rest#4]
Alejo, me funciono perfecto en servidor de desarrollo sobre windows, cuando lo probé en servidor de producción sobre linux obtuve

 PHP Fatal error:  Uncaught Error: Class 'AlejoASotelo\Andreani' not found in /home/public_html/CotizadorAndreaniTester.php:45

creo que el problema es que linux es case sensitive, me parece que los namespace, directorios , nombres de clases y archivos donde estan declaradasl las clases deben respetar mayúsculas y minúsculas

mas allá de eso, muy buen trabajo!!

**Comment by leandromp83** [comment]
Hola tengo el mismo problema con la implementación en producción en desarrollo (macOs) todo bien pero al llevar a linux tengo problemas.

**Comment by leandromp83** [comment]
el archivo vendro/alejoasotelo/andreani/src/andreani.php lo renombre vendro/alejoasotelo/andreani/src/Andreani.php y se soluciono. Pienso tambien lo mismo muchas gracias por semejante laburo.

**Comment by alejoasotelo** [comment]
Hola @leandromp83 @cruzdelsur3 lo voy a revisar asi lo arreglo!

Que versiones de PHP están usando?

Gracias por crear el issue y colaborar!

**Comment by cruzdelsur3** [comment]
PHP 7.4.12 (cli)

**Comment by leandromp83** [comment]
PHP 7.2.24-0ubuntu0.18.04.7

**Comment by leandromp83** [comment]
Alejo gracias a vos. !!!
