### ISSUE TITLE
Cambios en URL de Producción y QA

### ISSUE THREAD

**Issue by juliangorge** [alejoasotelo/andreani-sdk-rest#7]
Hola Alejo! Muchas gracias por compartir esta herramienta con nosotros!

Revisando Andreani.php propondría los siguientes cambios debido a modificaciones que se hicieron en Andreani:

const BASE_URL_DEV = 'https://apisqa.andreani.com';
const BASE_URL_PROD = 'https://apis.andreani.com';

Por otro lado, la cabecera pasó de X-Authorization-Token a "x-authorization-token"
$token = $response->headers['x-authorization-token'];

Tuve que modificar esto para que me funcione a mi
Espero que sirva a los demás.
Atentamente Julian

**Comment by alejoasotelo** [comment]
Hola Juan, un placer!

Lo reviso, particularmente no tuve problemas con las urls actuales (tengo sitios en producción funcionando). 

Voy a hacer pruebas con las nuevas urls para verificar que funcione todo ok y actualizo.

Gracias por la data!
