### ISSUE TITLE
Ver/avanzar/retroceder estados de un envío en QA

### ISSUE THREAD

**Issue by pabloldeoliveira** [alejoasotelo/andreani-sdk-rest#8]
Hola Alejo, primero que nada muchas gracias por la librería, nos ahorró bastante tiempo en un desarrollo sobre el que estamos trabajando.

Mi consulta es la siguiente, siempre trabajando en modo sandbox (QA) para poder integrar: cuando proceso una venta en mi sistema (es un e-commerce) primero genero una orden de envío con $ws->addOrden(...) y de ahí me es devuelta la etiqueta en PDF y el número de seguimiento. Ese número de seguimiento después puedo consultarlo para ver el estado en que se encuentra.

Con $ws->getOrden('NUMERO_ENVIO') recibo:
![image](https://user-images.githubusercontent.com/13597768/225387476-7d38eb3f-b888-48ea-a807-167670629de3.png)

Con $ws->getTrazabilidad('NUMERO_ENVIO') recibo:
![image](https://user-images.githubusercontent.com/13597768/225387693-cf354a7b-a7b7-4df1-8ae4-416238509f87.png)

Había leído en un issue que en QA el método getTrazabilidad no suele funcionar bien y puede devolver 500 o 404. A mí siempre me devuelve null, directamente. Pero si llamo directamente al endpoint https://apisqa.andreani.com/v2/envios/ (sin usar tu librería) obtengo esta respuesta:
![image](https://user-images.githubusercontent.com/13597768/225389641-6d207742-c439-4460-bfd7-96fc1542962c.png)

El problema es que al menos en QA no parece haber forma de hacer una simulación de los diferentes estados en los que puede encontrarse un envío (pendiente, en tránsito, visita a domicilio, entregado, etc...). Hay alguna manera de simular esto? O bien obtener todos los estados de envío posibles que trabaja Andreani internamente?

Saludos y gracias!

**Comment by alejoasotelo** [comment]
Hola Pablo, primero que nada me alegra que te haya servidor para tu proyecto!

Segundo, probaste usar API_V2 como parámetro en getTrazabilidad? De esta manera usaría la url: https://apisqa.andreani.com/v2/numeroAndreani/trazas sino usa: https://apisqa.andreani.com/v1/numeroAndreani/trazas (notese v1).

```php
$ws->getTrazabilidad($numeroAndreani, Andreani::API_V2);
```

Tengo que deprecar todo lo de la v1 porque casi no se usa y actualizar varios endpoints.

**Comment by pabloldeoliveira** [comment]
Hola Alejo, gracias por tu respuesta.

Efectivamente probé agregar el segundo param a getTrazabilidad pero igual me devuelve null. Supongo es porque estoy en QA.

Si uso getOrden recibo datos:
![image](https://user-images.githubusercontent.com/13597768/225706256-545cc16e-1a1d-4bbd-921f-1c5f3d9abaa8.png)

Ejemplo de como estoy usando las funciones:
![image](https://user-images.githubusercontent.com/13597768/225706415-f4714133-2ce0-438e-8095-aef4b83275c9.png)

Igual más allá de ese detalle, entiendo que si uno quiere simular el circuito que hace un envío desde que es despachado hasta que llega a destino es imposible en QA, o hay alguna forma de simular esto? Porque en QA me queda en "Pendiente de ingreso" y de ahí no se mueve obviamente.
![image](https://user-images.githubusercontent.com/13597768/225707483-010803fe-8d06-455c-b624-7749a3be0994.png)


Esto último es básicamente por la forma en la que necesito reflejar una especie de línea de tiempo con el circuito del envío, en el e-commerce que estoy desarrollando.

**Comment by alejoasotelo** [comment]
No puedo probarlo en QA porque no estoy encontrando mis credenciales de QA, pero estoy casi seguro que no funciona. Devuelve null y podes ver el response completo usando $ws->getResponse() (Si te interesa tenés mas info del response acá https://github.com/joomla-framework/http/tree/1.x-dev)

Ejemplo:
```php
$trazabilidad = $ws->getTrazabilidad($numeroAndreani, Andreani::API_V2);
if (is_null($trazabilidad)) {
  $response = $ws->getResponse();
  echo 'HTTP_CODE: ' . $response->code;
}
```

> Igual más allá de ese detalle, entiendo que si uno quiere simular el circuito que hace un envío desde que es despachado hasta que llega a destino es imposible en QA, o hay alguna forma de simular esto? Porque en QA me queda en "Pendiente de ingreso" y de ahí no se mueve obviamente.

Si, es es como decís, si querés simular el circuito vas a tener que simular algunas respuestas. En QA el estado te va a quedar congelado en "Pendiente de ingreso". En su momento hablé con la gente del webservice y me dijeron que debería devolver más datos, pero sigue así.

Por si te sirve ver la estructura te paso un ejemplo de respuesta de la trazabilidad de un envío generado la semana pasada.
Dato que no vi documentado, en el campo Ciclo puede aparecer otro valor que no sea "Distribution" (creo que cuando no pasan a retirar el envío y lo devuelven), por lo tanto, en mi caso si un $evento->Ciclo != "Distribution" no lo muestro.
Por último el *estado* del envío lo tomo del último evento así evito hacer 2 request a Andreani porque a veces tarda mucho en responder el webservice.

```json
{
    "eventos": [
        {
            "Fecha": "2023-03-07T09:21:56",
            "Estado": "Pendiente de ingreso",
            "EstadoId": 1,
            "Traduccion": "ENVIO INGRESADO AL SISTEMA",
            "Sucursal": "Sucursal Gen\u00e9rica",
            "Ciclo": "Distribution"
        },
        {
            "Fecha": "2023-03-08T07:22:52",
            "Estado": "Ingreso al circuito operativo",
            "EstadoId": 5,
            "Traduccion": "ENVIO INGRESADO AL SISTEMA",
            "Sucursal": "CABA- CIT ( NORLOG)",
            "SucursalId": 231,
            "Ciclo": "Distribution"
        },
        {
            "Fecha": "2023-03-08T10:32:38",
            "Estado": "En viaje",
            "EstadoId": 7,
            "Traduccion": "ENVIO CON SALIDA DE SUCURSAL",
            "Sucursal": "CABA- CIT ( NORLOG)",
            "SucursalId": 231,
            "Ciclo": "Distribution"
        },
        {
            "Fecha": "2023-03-08T14:09:58",
            "Estado": "En sucursal de destino",
            "EstadoId": 8,
            "Traduccion": "ENVIO LLEGA A SUCURSAL",
            "Sucursal": "MORENO (CENTRO)",
            "Ciclo": "Distribution"
        },
        {
            "Fecha": "2023-03-08T14:09:58",
            "Estado": "En custodia",
            "EstadoId": 9,
            "Traduccion": "ENVIO EN CUSTODIA EN SUCURSAL ANDREANI",
            "Sucursal": "MORENO (CENTRO)",
            "Ciclo": "Distribution"
        },
        {
            "Fecha": "2023-03-08T14:38:30",
            "Estado": "En custodia",
            "EstadoId": 9,
            "Traduccion": "ENVIO DISPONIBLE PARA SU ENTREGA EN SUCURSAL ANDREANI",
            "Sucursal": "MORENO (CENTRO)",
            "Ciclo": "Distribution"
        },
        {
            "Fecha": "2023-03-08T14:38:30",
            "Estado": "En custodia",
            "EstadoId": 9,
            "Traduccion": "ENVIO DISPONIBLE PARA SU ENTREGA EN SUCURSAL ANDREANI",
            "Sucursal": "MORENO (CENTRO)",
            "Ciclo": "Distribution"
        },
        {
            "Fecha": "2023-03-08T14:38:33",
            "Estado": "En custodia",
            "EstadoId": 9,
            "Traduccion": "ENVIO DISPONIBLE PARA SU ENTREGA EN SUCURSAL ANDREANI",
            "Sucursal": "MORENO (CENTRO)",
            "Ciclo": "Distribution"
        },
        {
            "Fecha": "2023-03-11T11:26:59",
            "Estado": "Entregado",
            "EstadoId": 18,
            "Motivo": "Entregado",
            "MotivoId": 16,
            "Submotivo": "Entregado en Sucursal Andreani",
            "SubmotivoId": 196,
            "Traduccion": "ENVIO ENTREGADO",
            "Sucursal": "MORENO (CENTRO)",
            "Ciclo": "Distribution"
        },
        {
            "Fecha": "2023-03-11T11:26:59",
            "Estado": "Entregado",
            "EstadoId": 18,
            "Motivo": "Entregado",
            "MotivoId": 16,
            "Submotivo": "Entregado por Mostrador",
            "SubmotivoId": 197,
            "Traduccion": "ENVIO ENTREGADO",
            "Sucursal": "MORENO (CENTRO)",
            "Ciclo": "Distribution"
        }
    ]
}
```

Y acá tenes la vista de cómo quedaría, aplicando un ordenamiento por fecha, agrupación por día y filtrando eventos != Distribution:

![imagen](https://user-images.githubusercontent.com/1103289/225725805-ea6c5952-f355-4fdb-8c68-9af9ab55fd0e.png)

**Comment by pabloldeoliveira** [comment]
Excelente Alejo, es perfecto ese ejemplo porque de ahí puedo cruzar los estados de envío que da Andreani con los de mi sistema. Mil gracias!

**Comment by alejoasotelo** [comment]
De nada Pablo, para lo que necesites chifla, un saludo!
