### ISSUE TITLE
No llegan datos como piso, depto u observaciones al generar etiqueta

### ISSUE THREAD

**Issue by pabloldeoliveira** [alejoasotelo/andreani-sdk-rest#9]
Buen día a todos, estoy con un inconveniente al generar etiquetas. Se generan bien, pero no llega toda la información dele destinatario en la etiqueta, específicamente piso/depto u observaciones. En el e-commerce que estamos desarrollando tenemos en una tabla columnas como piso, depto y observaciones, pero en el request que enviamos a Andreani no tenemos forma de mapear esos campos. Por ejemplo:

'destino' => [
                    'postal' => [
                        'codigoPostal'      => (string) $datos_direccion['codigo_postal'],
                        'calle'             => (string) $datos_direccion['calle'],
                        'numero'            => (string) $datos_direccion['numero'],
                        'localidad'         => (string) $datos_direccion['localidad'],
                        'region'            => 'AR-B',
                        'pais'              => 'Argentina',
                        'componentesDeDireccion' => [
                            [
                                'meta'      => 'piso',
                                'contenido' => (string) $datos_direccion['piso'],
                            ],
                            [
                                'meta'      => 'departamento',
                                'contenido' => (string) $datos_direccion['depto'],
                            ],
                        ],
                    ],
                ],

Aunque en el request podamos pasar los campos piso y depto, en la etiqueta no salen. Tampoco vemos que haya posibilidad de agregar un campo de observaciones (en el request también).

Qué podría hacer para que estos campos lleguen a la etiqueta?
Saludos y gracias!

**Comment by alejoasotelo** [comment]
Hola Pablo, cómo estás?

Hace un tiempo cambiaron las etiquetas que imprimen y me pasó esto que decís también, quitaron algunos datos. 

Podés hacer el reclamo a Andreani a ver si te agregan el dato y sino vas a tener que hacer tus propias etiquetas. Básicamente sería clonar las etiquetas de ellos, cambiarle los datos y agregar los que te falten.

Como comentario personal, tengo la sospecha de que el cartero no mira la etiqueta, se fijan en el código de barras del envío u otro identificador y ahí tienen todos los datos porque no se entiende que en sus etiquetas no agreguen esos datos.

**Comment by pabloldeoliveira** [comment]
Muchas gracias por la info Alejo!
